BASE: ['default.yaml']
MODEL:
  TYPE: swin
  NAME: swin_nano_patch4_window7_224
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 48 
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
